// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'create': string;
  'home': string;
  'title': string;
  'datePicker': string;
  'error': string;
  'errors': string;
  'form-style': string;
  'form': string;
  'input': string;
  'react-dropdown-select-input': string;
  'register': string;
  'show': string;
  'timeBox': string;
  'timePeriods': string;
  'titleContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
